version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: ./.deploy/Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "443:443"
    networks:
      - laravel
    environment:
      APP_URL: "http://localhost"
      APP_ENV: development
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: contacts_manager
      DB_USERNAME: contacts_manager
      DB_PASSWORD: password
    container_name: contacts_manager

  mysql:
    image: mysql:5.7.29
    restart: always
    tty: true
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: contacts_manager
      MYSQL_USER: contacts_manager
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
    networks:
      - laravel
    container_name: contacts_manager_db

volumes:
    db_data: